<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TaggedUnionVB.Generator</RootNamespace>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <NoWarn>$(NoWarn);NU5128</NoWarn>

    <!-- NuGet Package Info -->
    <PackageId>TaggedUnionVB.Generator</PackageId>
    <Version>1.0.0</Version>
    <Authors>Pac-Dessert1436</Authors>
    <Company></Company>
    <Description>A source generator that creates tagged union types for VB.NET, providing type-safe
      pattern matching capabilities similar to discriminated unions in functional languages.</Description>
    <PackageTags>VB.NET;SourceGenerator;DiscriminatedUnions;UnionType;CodeGenerator;Analyzer</PackageTags>
    <RepositoryUrl>https://github.com/Pac-Dessert1436/TaggedUnionVB.Generator</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Pac-Dessert1436/TaggedUnionVB.Generator</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <!-- Source Generator Required Settings -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IsRoslynComponent>true</IsRoslynComponent>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.8.0"
      PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4"
      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll"
      Pack="true"
      PackagePath="analyzers/dotnet/vb"
      Visible="false" />
  </ItemGroup>

</Project>